# Define workflow name.
name: TimeZone Test

# Controls when the workflow will run.
on:


  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:

  tae-sca:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    name: SCA Test on CentOS/x64

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - name: Test
        run: |
          timedatectl status
          sudo timedatectl set-timezone "Asia/Shanghai"
          timedatectl status


